version: "3.5"

networks: 
  mynetwork:
    name: mynetwork
    attachable: true    

services:


#docker run -v '/tmp/.X11-unix:/tmp/.X11-unix:rw' -v "/var/lib/.Xauthority:/headless/.Xauthority:rw" --rm -p 6901:6901 consol/centos-xfce-vnc
  novnc:
    image: accetto/ubuntu-vnc-xfce  
    environment:
      - VNC_PW=changeme
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /var/lib/.Xauthority:/home/headless/.Xauthority:rw
    ports:
      - "6901:6901"
    networks:
      - mynetwork
      
#docker run -v '/tmp/.X11-unix:/tmp/.X11-unix:rw' -e DISPLAY=:1 -v /var/run/docker.sock:/var/run/docker.sock harperaa/labtainer.master /docker-entrypoint
  labtainer:
    image: labtainer.master
    environment:
      - DISPLAY=:1 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - novnc
    entrypoint: ["/docker-entrypoint"]
    tty: true
    networks: 
      - mynetwork
